version: '3'
services:
  frontend-local:
    image: ferramenta-custos/frontend:local
    container_name: frontend_local
    environment:
      - BACKEND_HOST=127.0.0.1
      - BACKEND_PORT=8050
    build:
      context: ..
      dockerfile: ./docker/compose/local/Dockerfile
    ports:
      - '4200:4200'
